spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434170935842-u7ugvl9g23l9h30hldt5dc103ogu1nrr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: utX2_VgEAMVwAzV6ze9v
            client-secret: mK_YO2ElZi
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/naver
            scope:
              - nickname
              - email
              - profile_image

          #kakao:
            #client-id: f830ac604b909cbe2f28044801646ad4
            #client-secret: 8KYn1FyZUnVGk9AmVlQntZKPat7ERC1K
            #client-authentication-method: POST
            #client-name: Kakao
            #authorization-grant-type: authorization_code
            #redirect-url: http://localhost:9090/login/oauth2/code/kakao
            #scope:
              #- profile_nickname
              #- profile_image
              #- account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #네이버가 회원정보를 JSON으로 넘겨주는데, response라는 키값으로 리턴해줌

          #kakao:
            #authorization_uri: https://kauth.kakao.com/oauth/authorize
            #token_uri: https://kauth.kakao.com/oauth/token
            #user-info-uri: https://kapi.kakao.com/v2/user/me
            #user_name_attribute: id #카카오가 회원정보를 JSON으로 넘겨주는데, id라는 키값으로 리턴해줌